### ISSUE TITLE
lean-mode: display coercion

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean#124]

**Comment by soonhokong** [comment]
Let's say that we have a cursor at 'n' (marked with '^'):

``` lean
import data.int
using nat int

variables n m : nat
variables i : int

check n + i + m
      ^
```

@leodemoura, I'm implementing this one. For the current version that I'm working on, it shows

```
of_nat (n : nat)
```

I think it would be nicer if we can display

```
int.of_nat (n : nat) : int
```
1. Do you think it's good? Any other suggestions?
2. To implement, I need a full-name of coercion function (`int.of_nat` instead of `of_nat`) as well as its return type (`int`).

**Comment by leodemoura** [comment]
Some remarks
1- Coercions may be applied to arbitrarily big terms. The argument is not necessarily a constant. 

2- The coercions are not necessarily just a constant (e.g., of_nat). They can be derived one.
For example, it can be

```
      (λ (a : num), int_to_real (nat_to_int (num_to_nat a)))
```

This is a simple example since all coercions do not have parameters.

3- We can pretty print the coercion using `pp.full_names == true`, but this would be really bad for composite coercions like the one above. The result will be too big.
Moreover, why would we set an option for one kind of information (e.g., coercions), but not for others (e.g., type).

I think we can include the type of the coercion. The user may use `M-x lean-set-option` to change the pretty printing options. Including the argument may not be a good idea. It may be too big.

**Comment by soonhokong** [comment]
@leodemoura, I will drop by your office tomorrow morning.
