### ISSUE TITLE
lean-mode: show type info for an expression wrapped with parens

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean#135]
Follow-up of #133 and https://github.com/leanprover/lean/commit/ffc871ea8cc79bb2fdd8510a7a2bdc193c152755

**Comment by soonhokong** [comment]
@leodemoura, I've implemented this one. Please test it and let me know if you have an issue. I'm thinking about some improvement of this:
- Show extra-type for the closed-paren (in emacs, I can tell the position of corresponding open-paren)
- Highlight the expression wrapped by parens

**Comment by leodemoura** [comment]
It works really well.
Now, I'm wondering whether we should display just the type.
Most of the time, I just want to see the type. The expression is usually bigger and redundant since it is in the buffer. There very few cases where I want to see the expression too. Example: the expression contains many nested placeholders that have been filled by Lean. Perhaps, we should have an option to enable/disable the expression. I think it should be false by default since in most cases we want to see only the type. What do you think?

**Comment by soonhokong** [comment]
> Most of the time, I just want to see the type.

I agree.

> Perhaps, we should have an option to enable/disable the expression.

Right. I will add the option.

**Comment by soonhokong** [comment]
Added a customization-variable `lean-show-only-type-in-parens` (default value = `t`).
