### ISSUE TITLE
nested implicit arguments

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#143]
Something goes wrong with implicit arguments in the following example:

```
import logic.core.eq
open eq
section
parameters (A : Type) (foo : Π(f : Π(H : Π{a b : A}, a = b) (a b : A), a = b), Type)
check foo (λ H a b, H a b)
end
```

The arguments of H should be implicit, but the line with "check" is only accepted when I provide H with explicit arguments. The pretty printer prints this as
`foo (λ (H : ∀ {a b : A}, eq a b) (a b : A), H) : Type`
so without the implicit arguments (as expected).

**Comment by leodemoura** [comment]
I'm aware of this problem, but I never found a good solution for it.

The lean parser generate pre-terms. A pre-term does not contain metavariables, implicit arguments were not added, overloaded operators are modeled using `(choice op_1 ... op_n)`, etc.

In the first step (aka preprocessing), the elaborator converts a pre-term into a term with metavariables. 
The preprocessor "injects" metavariables for each implicit argument. However, it does that using the information that is already available. When processing (fun H a b, H a b), the preprocessor does not know anything about H. Since, the user typed (H a b), it will just add constraints that enforce that the type of H is of the form (Pi x, (Pi y, ...)).

After the unification constraints start to be solved, the type of H is assigned to a Pi with implicit arguments. This is why we get  `foo (λ (H : ∀ {a b : A}, eq a b) (a b : A), H) : Type`

I don't see an easy way to do what you want. One (possibly inefficient) option would be:
whenever we are preprocessing (f a), and the type of f is a metavariable ?M (remark: I'm omitting local constants to improve readability). Then, we case-split on
case 1)     ?M =?= (Pi (x : ?M1), ?M2 x)     

case 2)    ?M =?= (Pi {x : ?M1}, ?M2 x)  
                 f a ===>  f ?M3 a

Another solution is to try to solve some of the already generated unification constraints and hope ?M is assigned to some Pi-term. This solution is brittle, since we would only solve unification constraints that do not require search. Moreover, the order the term is preprocessed matters (the "already generated" part).

**Comment by avigad** [comment]
It seems a little contrived to want to specify not only the implicit arguments to a function, but the implicit arguments to the arguments to a function. Floris, does it come up natural situations? Will it happen often that a user gets frustrated if they cannot do this?

**Comment by fpvandoorn** [comment]
This does come up in natural situations, and I think completely disallowing it could be troublesome.

The natural situation where this comes up is in induction proofs. For example, you might prove by induction to `n` that `forall {k}, P(n,k)` and then the induction hypothesis becomes `IH : forall {k}, P(l,k)`. It can be a little nicer to have implicit arguments in the statement you're proving, but it's not really a big deal.

I encountered it in category.lean. There I define categories

```
inductive category (ob : Type) (mor : ob → ob → Type) : Type :=
mk : Π (comp : Π{A B C : ob}, mor B C → mor A B → mor A C), (...) → category ob mor
```

Now the recursion principle becomes

```
category.rec :
  Π {ob : Type} {mor : ob → ob → Type} {C : category ob mor → Type},
    (Π (comp : Π {A B C : ob}, mor B C → mor A B → mor A C) (id : Π {A : ob}, mor A A) 
(...)
```

so comp has implicit arguments. In this file it became problematic in the following example. The last argument of category.mk is the left identity, which has type `(Π {A B : ob} {f : mor A B}, comp id f = f)`. Given a category `Cat`, I get the following theorem immediately:

```
theorem id_left  : Π {A B : ob} {f : mor A B}, id ∘ f = f :=
rec (λ comp id assoc idr idl, idl) Cat
```

When I tried to define id_left with the arguments applied to the theorem (instead of having the theorem as universal statement), I had some trouble proving it. Both the following proofs raise errors

```
theorem id_left2 {A B : ob} {f : mor A B} : id ∘ f = f :=
rec (λ comp id assoc idr idl, idl) Cat -- gives some type mismatch error
theorem id_left3 {A B : ob} {f : mor A B} : id ∘ f = f :=
rec (λ comp id assoc idr idl, idl A B f) Cat -- gives as error that idl A B f is not a function 
--(though I don't know why that error is raised, we do not apply idl A B f to something)
--(the more I think about this, the more I think this is some unrelated other error)
```

This is a problem. The only way I know how to prove it is to give the type of "idl" explicitly in the lambda expression (and I can then give this type either with explicit or implicit arguments and both then work as expected). Also, if I change the implicit arguments in the last argument of category.mk to explicit arguments, so to `(Π (A B : ob) (f : mor A B), comp id f = f)`, even then the second proof still raises an error. Does this have to do with #141?

I just noticed, where the nested implicit arguments were really useful was in the definition of category itself:

```
inductive category (ob : Type) (mor : ob → ob → Type) : Type :=
mk : Π (comp : Π{A B C : ob}, mor B C → mor A B → mor A C)
           (id : Π {A : ob}, mor A A),
            (Π {A B C D : ob} {f : mor A B} {g : mor B C} {h : mor C D},
            comp h (comp g f) = comp (comp h g) f) →
           (Π {A B : ob} {f : mor A B}, comp f id = f) →
           (Π (A B : ob) (f : mor A B), comp id f = f) →
            category ob mor
```

If "comp" doesn't have implicit arguments, stating the identities is much more ugly.

---

@leodemoura, I think I understand the problem. I wouldn't mind if nested implicit arguments aren't fully supported, and always choosing "case 1". Is that currently what's happening? This is still confusing, but I also see no good way around it (case-splitting every time seems too inefficient). Of course, when the type of f is (partially) given, it should choose the case corresponding to the known information in the type. One thing which should be changed is that the pretty printer and the parser should agree on whether the arguments are explicit or implicit.

```
import logic.core.eq
open eq
section
parameters (A : Type) (foo : Π(f : Π(H : Π{a b : A}, a = b) (a b : A), a = b), Type)
check foo (λ (H : Π{a b : A},_) a b, H) -- both parser and pretty printer give implicit argument
check foo (λ (H : Π(a b : A),_) a b, H a b) -- both parser and pretty printer give explit argument
check foo (λ H a b, H a b) -- parsed as explicit arguments, but pretty printer gives implicit arguments (and hovering over H gives implicit arguments)
end
```

**Comment by avigad** [comment]
I still haven't thought through all this carefully, but here is one thought. Soon Leo will implement a structure command like Coq's so we can write something like

structure category (ob : Type) (mor : ob → ob → Type) : Type := mk
{
  comp : Π{A B C : ob}, mor B C → mor A B → mor A C,
  id : Π {A : ob}, mor A A, 
  ...
}

This would be just syntactic sugar for the definition above, but under the hood it could define the recursor and eliminator with everything explicit, and then go back and define the projections with the appropriate implicit arguments. Would that help?

By the way, does it help to add an explicit "@" in id_left3, like this?

  rec (λ comp id assoc idr idl, @idl A B f) Cat

(Does that even make sense?)

**Comment by leodemoura** [comment]
@fpvandoorn here are some additional comments.

We should not rely on "binder annotation" propagation. The implicitness is just an annotation used by the preprocessing step described in my previous message. From the point of view of the kernel,
      `(fun {A : Type} (a : A), a)` and `(fun (A : Type) (a : A), a)` are definitionally equal.

Moreover, the "binder annotation" propagation may produce very counter-intuitive behavior. For example, consider this example:

```
       fun (f : Pi {A : Type}, A -> A),
          fun g,
               g a = a /\ g = f
```

Lean will reject this formula, but if we had full "binder information" propagation, it may be considered correct. The term `g = f` forces `g` and `f` to have type `Pi {A : Type}, A -> A`. Then `g a` should have be treated as `g ?A a`, but we have already processed `g a`. The case-split approach would have solved this instance, but it is too expensive.

Actually, it is more expensive than I described in my previous message, I only considered "case-splitting" on applications. This is only enough for the strict implicit annotation `{{ ... }}`. For the `{}`, we would have to case-split on _any_ term `t` s.t. type of `t` is of the form `?M ...`. This is not feasible.

As far as I know, no system implements "binder annotation propagation". 

Users should assume that lean will only use explicitly provided binder annotation.

The term `(fun f a, f)` is treated as "no annotation" provided.

Under this interpretation, the definitions `id_left2` and `id_left3` are indeed type incorrect.
The correct formulation would be

```
      theorem id_left2 {A B : ob} {f : mor A B} : id ∘ f = f :=
      rec (λ comp id assoc idr idl, idl) Cat A B f 
```

Finally, regarding the comment: "One thing which should be changed is that the pretty printer and the parser should agree on whether the arguments are explicit or implicit". They do agree.  Note that

```
   check foo (λ H a b, H a b)
```

is a "pre-term" full of missing information. It should be viewed as hint to the elaborator.
When we type just `H`, it means "no annotation".
The elaborator fills the holes and produces a term that equivalent to this one modulo missing information and annotations. If we type the output produced by the pretty printer, Lean will produce the same output. 
Is it possible to make sure `H` is displayed with explicit arguments? Yes, it is, but we would have to perform an "annotation erasure step" in the unifier. In the unifier, we will solve a constraint

```
       (?M ...)   =?=   (Pi {...}, ...)
```

where `?M ...` is the metavariable application representing the type of `H`. We solve this constraint by assigning `?M` to the closure of `(Pi {...}, ...)`. So, to get the behavior you requested, we would have to erase all the annotations in the right hand side before performing the assignment. This seems to be a lot of extra work for very little gain. It is not even clear we are gaining anything, since the currently produced output is not really incorrect.

**Comment by fpvandoorn** [comment]
Can you explain why `id_left3` gives the error it gives? The proof is

```
rec (λ comp id assoc idr idl, idl A B f) Cat
```

I thought it would do something like the following. First, the preprocessor gives `idl` a preliminary type `Pi (x : ?M_1) ( y : ?M_2 x) (z : ?M_3 x y), ?M_4 x y z` (where I ignored the other variables in the local context). Then the unifier would try to unify (among other things):

```
Pi (x : ?M_1) ( y : ?M_2 x) (z : ?M_3 x y), ?M_4 x y z
=?=
∀ {A B : ob} {f : mor A B}, comp id f = f
```

And this will unify the metavariables ?M_i in the expected way.

I'm confused why this gives the error "function expected at `idl A B f`". Usually you get that error when you try to apply that term to something, right? Do we do that here?

---

About the pretty printer: I agree that it is very little gain, since the output of the pretty printer is indeed correct. So if there's no easy solution, then it's fine to keep it the way it is. I'm just confused (and users might get confused) that apparently Lean stores the type of `H` with implicit arguments `H : ∀ {a b : A}, a = b` but doesn't complain that we apply it to `a` and `b` in our pre-term.

**Comment by fpvandoorn** [comment]
@avigad: sorry, I forgot to answer your question. Yes, `@idl` does make sense, and if we give the type of `idl` explicitly in the abstraction, it works exactly how you would expect. However, with implicit type (in your example), it gives exactly the same error.

**Comment by leodemoura** [comment]
@fpvandoorn:  I spent the whole day analyzing `id_left3`.  It turns out the failure in this theorem has nothing to do with implicit arguments, but a limitation in the higher-order unification procedure.
First, let's consider the shorter example (the example is nonsensical but it produces the same failure).

```
abbreviation Prop := Type.{0}
variable eq {A : Type} : A → A → Prop
infix `=`:50 := eq

variable ob  : Type.{1}
variable mor : ob → ob → Type.{1}

inductive category : Type :=
mk : Π (id : Π (A : ob), mor A A),
     (Π (A B : ob) (f : mor A A), id A = f) → category

abbreviation id (Cat : category) := category.rec (λ id idl, id) Cat
variable Cat : category

theorem id_left (A : ob) (f : mor A A) : @eq (mor A A) (id Cat A) f :=
@category.rec (λ (C : category), @eq (mor A A) (id C A) f)
  (λ (id_1  : Π (T : ob), mor T T)
     (idl_1 : Π (T : ob), _),
     idl_1 A A f)
  Cat
```

The `id_left` theorem is this example, produces a constraint of the form:

```
     ?M A f id A A f ≈ (id (mk id a) A) = f 
```

After one "imitation" step, it is reduced to

```
     ?M1 A f id A A f ≈ (id (mk id a) A)
     ?M2 A f id A A f ≈ f
```

The `?M1` constraint has no solution unless we reduce the right-hand-size to `(id A)` using delta and iota reduction. When solving "flex-rigid" constraints, Lean will first try to solve the flex-rigid constraint without performing any reduction, if it fails, it backtracks, reduce and try again. This extra case-split is too expensive. So, we started looking for optimizations. We conjectured that if all arguments on the left-hand-side are local constants, then the extra case-split is unnecessary. The example above shows this conjecture is false :-( 
@avigad Do you remember this discussion? It seems this extra case-split will keep bugging us.
One fix is to always perform the "case-split", but it has a huge impact on performance. 
Jeremy and I tried that before and it was disaster (in terms of performance).
I tried again, and got similar bad results. The whole library can be compiled under 2 secs on my computer. If we always case-split the runtime is bumped to 25 secs.
Another workaround is to have a flag that enables the "extra" case-split. This is not nice. First, the error message is super weird, and does not provide any hint to the real problem. I think very few users will remember to turn on this flag.
Another "hack" is to perform the additional case-split IF the right-hand-side contains a local constant that is not on left-hand-side (in the example above, the right-hand-side contains the local constant `a`). Perhaps this is not too hackish since the only way to get rid of this extraneous local constant is by reduction. That is, we will eventually fail to solve the constraint unless we reduce. This may be a reasonable compromise.

Note that, this is also another example that shows that the order we solve the constraints matters. Minor variations of this example will work. In these variations, the constraint ?M is assigned before we try to solve

```
     ?M A f id A A f ≈ (id (mk id a) A) = f 
```

The whole experience today also suggests another heuristic for ordering constraints. We should solve first flex-rigid constraints where the right-hand-side is already in weak-head-normal form.

**Comment by leodemoura** [comment]
@avigad I found another source of brittleness. In the current version, we don't add the extra case-split for reducing the right-hand-side of a flex-rigid constraint IF the left-hand-side contains only local constants

```
     ?M l_1 ... l_k  =?=  t
```

This is a source of brittleness since the we may have another constraint on ?M which contains arguments that are _not_ local constatns. 

```
     ?M ... (idpath ...) =?=  t
```

Here is an actual example from our libraries.

```
?M.77.7 A g p x y q w r y q ≈ concat.{?8.68} A w (g x) (g y) (concat.{?8.68} A w x (g x) r (p x)) (ap.{?8.68 ?8.68} A A g x y q)

?M.77.7 A g p x y q w r x (idpath.{?8.68} A x) ≈ concat.{?8.68} A w (?M.77.23 A g p x y q w r x (idpath.{?8.68} A x)) (g x) (?M.77.25 A g p x y q w r x (idpath.{?8.68} A x)) (?M.77.26 A g p x y q w r x (idpath.{?8.68} A x)) 
```

If we always case-split, then none of our theorems break, and Floris's new module also goes through, but it is super expensive (10x overhead). I'm still trying to find a compromise by rearranging the priority queue. For example, the example above can be dealt by always processing flex-rigid constraints with non-local constant arguments first. Sometimes I feel we will have to keep tweaking this procedure forever :-(

**Comment by avigad** [comment]
Wow, how depressing! Higher order unification + computation is bad news. But don't worry, there has to be a reasonable solution.

I think I understand the issue. In the constraint,

```
   ?M A f id A A f ≈ (id (mk id a) A) = f 
```

there are really two "id"'s: one is a local variable introduced by the recursor, and the other is the id function. So the example could be less confusingly written

```
 ?M A f i A A f ≈ (id (mk i a) A) = f
```

Right?

The heuristic of doing the case split when the RHS contains extra local constants seems reasonable. It seems to cover the case of projections from a structure (since a projection will only mention previous fields, but the recursor introduces local constants for every field of the structure). So we would have to work harder to find exotic cases where that fails, i.e. where the unifier still has to reduce to find the solution. (Or maybe our modified conjecture is that _that_ can't happen.) Does that heuristic hurt performance?

Trying to reorder constraints also sounds like a good idea, though harder. The "tweaking" won't bother me if at the end we can still produce a sensible description of the algorithm and its properties. The problem (higher-order unification + reduction) is inherently delicate, and one would expect the solution to be subtle. As long as the solution is humanly understandable, it is fair game.

A third solution (not incompatible with the others) is to arrange things so that the user is guided towards solutions that do not have these problems. For example, if I understand correctly, there are no problems if enough types are provided explicitly, or the "f" is taken outside the recursion (so the recursor returns the id_left component, not applied). This means a "structure" command will have no trouble defining the structure and projections, and this example goes away.

Similar problems would come back with other inductive definitions with multiple constructors (like mk1, mk2). But if there is a function definition package that does the right things, then the user is less likely to write down recursions like this. This isn't a perfect solution, but we want users to have some mental picture of what the elaborator can and cannot do well, and have idioms that enable them to use it well. Induction, recursion, and substitution are the difficult cases, so Lean should provide "appropriate" ways of doing these.

**Comment by leodemoura** [comment]
@avigad: yes, there are two `id's`: the local constant `id` and the abbreviation `id`.

So far, for all my experiments (with reordering constraints) "broke" something. The file `hott/path.lean` contains 2 "very brittle" definitions. That is, subtle changes in the order the constraints are processed make them fail to be elaborated.

The definitional package and structure command (aka projection generator) would definitely minimize the problem. Using tactics would also help since we can control much better the order the constraints are generated.

**Comment by leodemoura** [comment]
I submitted the following commit: https://github.com/leanprover/lean/commit/187661aa6a2ee088fe5cdd9bb73db6a6b846c0f6

Now, Lean can handle definitions such as

```
theorem id_left3 {A B : ob} {f : mor A B} : id ∘ f = f :=
rec (λ comp id assoc idr idl, idl A B f) Cat
```

We don't need any special configuration option. There is no negative impact on performance.

We can also force the additional case-split by using

```
set_option unifier.computation true
```

I didn't change the order the constraints are processed.
The main modification is: we also consider the additional case-split on flex-rigid constraints whenever the rhs contains a local constant that is not in the lhs. The motivation is to try to get rid of it.

**Comment by avigad** [comment]
Excellent! Now Floris will have to work harder to find something that breaks the unifier. :-)

So the only place Lean does not consider the additional case split is where the LHS has only local constants, and all the local constants on the RHS are among those on the LHS.

The RHS can have metavariables, right? That would make the solution brittle in the sense that solving for one of those variables first could force a computation that the unifier would not do otherwise.

But perhaps in most cases the RHS already has all the local constants that are needed. And maybe in that case, if all the relevant local constants are on the LHS, the "conjecture" holds: anything the unifier can solve by reducing the RHS, it can also solve without reducing.

**Comment by leodemoura** [comment]
The RHS may contain metavariables. Note that metavariable assignments never contain local constants. The RHS may contain a term `(?M l_1 ... l_k)` where `?M` is a metavariable and `l_i`'s are local constants, but `?M` itself can never be assigned to a term containing local constants. So, RHS always contains all local constants that may occur in it.

**Comment by fpvandoorn** [comment]
Great! The fix to reduce flex-rigid constraints when there is a local constant on the right which is not on the left seems reasonable.

> > > Now Floris will have to work harder to find something that breaks the unifier. :-)

I'll try :-)

I think this issue can be closed. The original issue is cleared up, and the motivating confusion (which was that neither id_left2 nor id_left3 type-checked) is solved.
