### ISSUE TITLE
eldoc mode and company mode are not enabled on new file

### ISSUE THREAD

**Issue by avigad** [leanprover/lean#146]
If I enter

  emacs test.lean

for a new file and start typing, I get errors like

  eldoc error: (wrong-type-argument characterp nil)

and if I hit tab I get

  company not enabled

If I save the file, leave emacs, and start again, everything is o.k. If, in emacs, I open a new file test2.lean, I get

  File mode specification error: (wrong-type-argument characterp nil)

and the same behavior. If I start typing, save the file, kill the buffer, and then load the file again, it is o.k.

My .emacs file follows the instructions in lean/src/emacs/README.md

**Comment by leodemoura** [comment]
I submitted a fix for `lean --server` https://github.com/leanprover/lean/commit/87d7391d7af20cf9613766bd7825c39b3c2ad0f2

The problem is that `lean-mode` was sending a `VISIT file` command, but `lean --server` was signing an error saying the file did not exist. Now, it does not generate the error, and assumes it is an empty new file. 

The problem is not completely fixed. I'm still getting
             eldoc error: (wrong-type-argument characterp nil)

**Comment by soonhokong** [comment]
@avigad, does Leo's fix 87d7391 solve the problem? If not, please let us know.

**Comment by soonhokong** [comment]
Let me close this one. Please feel free to reopen it if you have an issue.
