### ISSUE TITLE
lean-mode for external users

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#170]
Most users will not work on the Lean standard library, but use it.

The TAGS file must be automatically detected. Possible trick: the default location for the TAGS file is  `[lean-binary-path]/../library/TAGS`

An emacs menu item for creating .project files.

**Comment by leodemoura** [comment]
If I open a file at `tests/lean/run`, and press `M-.` over `Prop` emacs is still asking me the `TAGS` file location.

**Comment by soonhokong** [comment]
@leodemoura, this can happen when `lean/library/TAGS` file do not exist. Could you check that that is the case?

**Comment by soonhokong** [comment]
If you work inside of library and press <kbd>M-.</kbd>, lean-mode automatically generates/updates `TAGS` file. However if you edit a file which does not belong to the library, the generation/update does not happen. If you want this feature, we can add it. 

I thought that this could be too much since we need to generates `TAGS` for all entries in `LEAN_PATH`.

**Comment by leodemoura** [comment]
Most users will not work inside of library. Moreover, the TAGS files will be there. So, there is no overhead.

It would be a pity if users could not browse the library by using commands such as `tags-apropos`.
As we discussed before, we want to wrap this command as a `lean-global-search` command.
