### ISSUE TITLE
another coercion bug

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#203]
I think I found another coercion bug. I tried to do the fully bundled approach for categories:

```
  abbreviation objects [coercion] (C : Category) : Type
  := Category.rec (fun c s, c) C

  abbreviation category_instance [instance] (C : Category) : category C
  := Category.rec (fun c s, s) C
```

This gives error that `C` has type `Category` instead of `Type` (in the application `category C`).

[The full file can be found here](https://github.com/fpvandoorn/lean/blob/master/library/algebra/category.lean#L185)

**Comment by leodemoura** [comment]
The coercions to `Type` were originally meant to allow the user to write

```
variable c : Category   
```

instead of 

```
variable c : carrier Category   
```

Similarly, the coercions to function-class allows us to write

```
F f
```

instead of

```
morphism F f
```

In the current implementation, none of them are considered for arguments.
That being said, the examples in your file are reasonable, and we can extend the coercion mechanism to cover them.

**Comment by avigad** [comment]
Don't you mean this?

```
  variable C : Category
  variable c : C
```

instead of

```
  variable C : Category
  variable c : objects C
```

That is what Floris is doing.

It is like 

```
  variable G : Group
  variable g : G
```

instead of 

```
  variable G : Group
  variable g : carrier G
```

**Comment by leodemoura** [comment]
Yes, I meant this

```
  variable C : Category
  variable c : C
```

Sorry about that.
