### ISSUE TITLE
linja on cygwin

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#206]
linja does not work on Cygwin anymore.
The problem is the generated ninja files.
On Cygwin, the files will have the prefix /cygdrive/c
ninja is a windows application, and gets confused with the prefix.
I didn't manage to find a ninja for Cygwin.
Possible solutions:
1) Hack: remove the prefix /cygdrive/c when generating the ninja file
2) Use relative paths. I know this creates problems for flycheck, but at least we will be able to compile lean on Cygwin, and use the command line tools.

**Comment by soonhokong** [comment]
Let me fix one on Monday with a windows machine on my hands. I'm curious why it worked before and then doesn't work now.

When there is no `ninja` available in the system, `linja` downloads the source code of `ninja` and build one for cygwin. I think what happened is that linja found ninja for native windows and used it because we are using the same machine to test for cygwin and native windows platform. @leodemoura, could you check if that is the case?

**Comment by leodemoura** [comment]
@soonhokong yes this was the source of the problem.
After I hid the native `ninja` from cygwin, `linja` downloaded the source code and compiled the cygwin version automatically. The build and tests were executed successfully.
