### ISSUE TITLE
lean-fill-placeholder gives parameters explicitly

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#227]
When executing C-c C-f on the placeholder below, the resulting term does not typecheck, because `foo` gets the argument `A` explicitly.

```
import logic.eq
section
parameter (A : Type)
definition foo (a b : A) := a = b
theorem bar (a b c : A) (H1 : foo a b) : Π (H2 : foo b c), foo a c :=
λ(H2 : _), eq.trans H1 H2
end
```

**Comment by leodemoura** [comment]
@soonhokong we need a way to stabilize this feature. In the current version, the only way to make sure that a pretty printed will be parsed is to print all implicit information and use fully qualified names. The main drawback is that no user will want to "pollute" their file with this kind of term.
I'm open to suggestions. I don't see any reasonable solution. There are several issues (I listed some in the end of the comment).
One possibility is to ask Lean to print the synthesized term with increasing amount of detail, until we find one configuration that is accepted. 
Another possibility is to simply disable this feature. 

Here is a list of issues:
1- `c` is a coercion, and the synthesized term uses `c`, by default the pretty printer will not display coercions. This may create problems since the elaborator may fail to select `c` because there is not enough information. Workaround: display all coercions.

2- The synthesized term may contain overloaded symbols. Workaround: we should have an option that displays the "short name" only if the symbol is not overloaded. 

3- The synthesized term may contain implicit arguments that cannot be synthesized by solving unification constraints. This can happen when the term was synthesized using class-instance resolution and/or tactics. Workaround: we should have an option that will display any implicit argument that cannot by synthesized using higher-order pattern matching.

4- We need to save all section parameters in the "information manager". After we process the file, and the user requests information about a placeholder `_`, lean doesn't know anymore what are the section parameters. This is why it prints `foo A b c` instead of `foo b c`. 

5- The annotations about implicit arguments cannot be fully "trusted". Just because we can infer that a parameter is "implicit" in a fully elaborated term, it doesn't mean Lean can do it when some of the information is suppressed.

**Comment by soonhokong** [comment]
By the time I added, I underestimated the complexity of this problem. Now, it seems it takes much time to polish.

@fpvandoorn and @avigad, could you tell us when and why you've used this feature (if any)?

**Comment by avigad** [comment]
I have not done that much formalizing since I knew how to use that feature.
To me, it does not seem to be high priority. Usually, if the elaborator can
fill in a place-holder, I am happy to leave it as an underscore. At worst,
I do not mind correcting the term by hand.

In the long run, when we use more automation to fill in place holders,
there will be more difficult questions about what information to put into
the proof script. For example, we may do a long and expensive resolution
search, and at the end maybe we want to record the facts that were used in
the proof, to speed up processing in the future.

I am curious to hear what Floris thinks, but my inclination would be to
defer better handling of this to a rainy day.

**Comment by fpvandoorn** [comment]
For me it's also not high priority. I sometimes use it in the way Jeremy describes. I write a placeholder, and let the elaborator fill it in, but then want to add the term to the proof term to make the elaboration easier on all future compilations. It's not a critical feature for me, but it's occasionally useful. I agree with Jeremy that we can defer better handling to later.
