### ISSUE TITLE
definition cannot be class?

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#228]
I get an error when I write

```
definition foo [class] (...)
```

Is this intended? I think some classes can be definitions instead of inductive types.
(I wanted to define `definition subsingleton [class] (A : Type) := ∀⦃a b : A⦄, a = b` which I think is useful, but might need a different name (suggestions?))

EDIT: the same happens if I want to declare a opaque definition to be a class.

**Comment by leodemoura** [comment]
Yes, this is intended. Lean will only consider `C` to be a class if terms `C a_1 ... a_n` are in weak-head-normal-form. If `foo` is a transparent definition, then `foo` will never be accepted as a class.
If we mark `foo` as opaque, recall that it is still transparent in the file where it was defined. Thus

```
opaque definition subsingleton [class] (A : Type) := ∀⦃a b : A⦄, a = b
```

is still not a valid class definition. The only way to make it a class in the file where it was defined is to use the `irreducible` command and then use the `class` command. It would be something like:

```
definition subsingleton (A : Type) := ∀⦃a b : A⦄, a = b
...
-- prove theorems that rely on the actual definition
...
irreducible subsingleton  -- now subsingleton is also opaque in this file
class subsingleton -- now subsingleton is a class
```

That being said, I think this idiom is horrible. Last week, I was discussing it with Jeremy.
My suggestion is to allow only inductive datatypes (and records) to be classes.
Then, it is super simple to explain to users what can be a class. The rule would be simple and we don't lose much. The `subsingleton` example can be wrapped as a datatype.

```
inductive subsingleton [class] (A : Type) : Prop :=
intro : (∀ a b : A, a = b) -> subsingleton A

definition subsingleton.elim {A : Type} (s : subsingleton A) : ∀(a b : A), a = b :=
subsingleton.rec (fun p, p) s
```

After we add records, it will be even easier to do this kind of "wrapping".
We can also make `subsingleton.elim` an instance of the class `eq`. Then, it will be automatically used whenever we have to prove an equality of a subsingleton type. Example:

```
definition subsingleton.elim [instance] {A : Type} (s : subsingleton A) : ∀ (a b : A), a = b :=
subsingleton.rec (fun p, p) s

section
  variable A : Type
  variable s : subsingleton A
  include s
  theorem tst {a b c : A} : a = b ∧ a = c ∧ b = c :=
  and.intro _ (and.intro _ _) 
end
```

Finally, I don't see how to eliminate the whnf requirement. If we don't force `C a_1 ... a_n` to be in weak-head-normal-form, then whenever we need to check whether a term `t` is a class, we would have to reduce it and track if in the reduction sequence there is a term of the form `C a_1 ... a_n`.
Moreover, the reduction sequence may have multiple terms of this form. We can even have `C a_1 ... a_n` and `D b_1 ... b_m`. So, it would not even be clear in which class `t` is.

Regarding the name, I like `subsingletion`.
In the HoTT book they also call it `h-proposition`.
 Actually, in the HoTT book, the definition is called `isProp`, and `hProp` is `Sigma A : Type, isProp A`.
I think it would be confusing since we have `Prop`.

**Comment by leodemoura** [comment]
@avigad @soonhokong Any thoughts?

**Comment by avigad** [comment]
I don't feel strongly about this, but making the user wrap every class
definition as an inductive definition seems to be an unnecessary hoop to
jump through. I would prefer to have the option of doing an ordinary
definition and marking it irreducible.

Maybe there is nicer sugar for that: e.g. we make the user write

  definition foo := ....

  class foo

in separate lines, and the "class" command marks foo as irreducible. (The
user can still use "[class]" with inductive definitions.)

That still may be confusing, but if the user writes

  definition foo [class] := ...

the error message can say "A class identifier must be irreducible. Use the
command 'class foo' to declare the instance and mark it irreducible."

**Comment by leodemoura** [comment]
@avigad We still have the issue that basic theorems must be defined between `definition foo` and `class foo`. By "basic", I mean theorems that depend on the actual definition. 
You say wrapping feels like a unnecessary hoop, but the approach using `irreducible` and performing operations in the right sequence seems very hackish. It is like selling a car and saying: "if you don't execute the operations in the right order, it will explode".

BTW, you suggest additional notation for making the idiom `opaque definition -> key theorems -> irreducible -> class` more convenient to use. The same can be done the wrapping approach.
As I said, after we have records, the wrapping will be super easy to be performed.

Now, suppose we are writing documentation for the class-instance resolution. We have to explain what is a class. My suggestion is: "Any (parametric) inductive datatype can be marked as a class". It is precise, and easy to understand. Now, consider the "opaque definition" approach. We have to explain much more: "opaque vs transparent" definitions, irreducible vs reducible, weak-head-normal-form, why transparent definitions cannot be classes.

Finally, there is yet another problem with the approach based on `opaque definitions`. Even if we perform the operations in the right sequence, we would still have a deficient solution. As I pointed out last week, `int` does not compute in the kernel. The key problem is that `int` must be opaque because we want it to be a class. Since, it must be opaque, `int.psub` and `int.rep` must also be opaque. The functions `int.psub` and `int.rep` are used everywhere. So, almost any computation on `int` will get stuck. Note that _all_ major systems based on type theory (e.g., Coq, Matita, Agda) `int` computes in the kernel.

**Comment by fpvandoorn** [comment]
I'm perfectly fine restricting classes only to inductive definitions. I was hoping for a transparent class, but I can see the problems with that. And using an opaque definition is pretty similar to using an inductive definition (at least in this case), because currently my code looked like this, which has practically the same behavior as Leo's inductive proposal.

```
opaque definition subsingleton (A : Type) := ∀⦃a b : A⦄, a = b

namespace subsingleton
protected theorem intro {A : Type} (H : ∀a b : A, a = b) : subsingleton A := H
protected theorem elim  {A : Type} (H : subsingleton A) : ∀(a b : A), a = b := H
end subsingleton
```

Question: why do we want `int` to be a class? In most other classes it doesn't matter which element is synthesized by Lean, but if you synthesize an integer, it matters a lot which one you choose... Or are classes for things other than term synthesis?

Note: currently, giving a (transparent) definition and then an instance is accepted by Lean:

```
definition subsingleton (A : Type) := ∀⦃a b : A⦄, a = b
protected definition prop.subsingleton [instance] (P : Prop) : subsingleton P := 
subsingleton.intro (λa b, !proof_irrel)
```

This should lead to an error. (if I write this, then the library breaks at the weirdest points, not involving subsingletons in any kind. I'm assuming that Lean then starts trying to prove that some equalities hold by trying to prove their type is a subsingleton)

**Comment by avigad** [comment]
Leo, you have convinced me that your proposal is best.

@fpvandoorn: the source and target of a coercion also has to be a class, so the same issues arise there, if we want to cast to/from int.

**Comment by leodemoura** [comment]
> This should lead to an error. (if I write this, then the library breaks at the weirdest points, not involving subsingletons in any kind. I'm assuming that Lean then starts trying to prove that some equalities hold by trying to prove their type is a subsingleton)

The issue will be solved after we restrict classes to inductive datatypes only.

**Comment by leodemoura** [comment]
@fpvandoorn  update for:

> Note: currently, giving a (transparent) definition and then an instance is accepted by Lean:
> 
> ```
> definition subsingleton (A : Type) := ∀⦃a b : A⦄, a = b
> protected definition prop.subsingleton [instance] (P : Prop) : subsingleton P := 
> subsingleton.intro (λa b, !proof_irrel)
> ```

The `[instance]` is accepted because we are actually defining an instance for `eq`.
I think this is very confusing and may produce very counter-intuitive behavior. 
We should force users to declare the class before defining its instances.
That is, the user would be forced to use `[class]` or the `class` command.
We will get an error if we try to define an instance of something that is not marked as a class.
What do you think?

**Comment by avigad** [comment]
This sounds right to me.

**Comment by fpvandoorn** [comment]
Yes, that also sounds good to me.
