### ISSUE TITLE
bugs when splitting category.lean

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#231]
I'm in the process of splitting category.lean in different files, and I encountered some bugs (I think) in this file:
https://github.com/fpvandoorn/lean/blob/master/library/algebra/category/morphism.lean

First, in the following snippet, `C` is not available as implicit argument to `hom`

```
parameters {ob : Type} {C : category ob}
include C
variables {a b : ob} {f : hom a b}
```

Second, in the inductives defined below that the term `@hom _ C a b` is not correctly elaborated for some reason (`@hom ob C a b` _is_ accepted).

**Comment by leodemoura** [comment]
In the current version, the `include` command only affects definitions. What kind of semantics do you have in mind?

**Comment by fpvandoorn** [comment]
I thought that when writing `include C`, `C` would be available for term synthesis anywhere in that section. That's the reason we want to use `include`, right? The fact that `C` then must be an argument to every definition in the section is then only a consequence, because we cannot see from just the type of a theorem whether `C` is used in its proof.

I think this is useful, because `C` could be used in other variables (above example), and could be useful for the `check` command, defining notations and probably other things.

**Comment by leodemoura** [comment]
> I thought that when writing include C, C would be available for term synthesis anywhere in that section. 

The semantics is `C` is added as an argument for every definition, and consequently it is available for automation. 

> That's the reason we want to use include, right?

Yes, this is exactly what it does. `C` is available for processing theorems and definitions.

I realize the feature you want is useful. It helps to elaborate the type of a variable.
However, it requires a different mechanism since it doesn't make sense to add `C` as argument to every variable/parameter in the section.

**Comment by leodemoura** [comment]
I submitted the following change to address this issue.
Now variables (and `check` command) have access to _all_ section variables.
The `include` command is still only relevant for `definition`s and `theorem`s.

**Comment by fpvandoorn** [comment]
This sounds like a good fix, the `check` command and variables will (almost) never be the bottleneck for the elaborator.

However, the fix doesn't seem to be working properly. When writing

```
variables {c d : ob} {h : hom c d}
```

I still get the error `failed to synthesize placeholder ob : Type, c : ob, d : ob ⊢ category ob`

Also, the second problem in the opening post, I just don't understand what the problem is from the error message:

```
invalid local context when tried to assign
  ob
containing 'ob', to placeholder '?M_1', in the empty local context
the assignment was attempted when trying to solve
    type mismatch at application
      @hom ?M_1 C
    term
      C
    has type
      category ob
    but is expected to have type
      category ?M_1
```

It also seems that universe levels are not added properly for `check` command. When writing

```
check hom a b
```

I get the error `invalid reference to undefined universe level parameter 'l_2'`

**Comment by avigad** [comment]
@fpvandoorn:

I may be experiencing a similar problem. I have been working through the
definition of semisimplicial types, and having fun with your definition of
category. But I noticed that in one place I had to use the following
definition:

---

definition BD0 : functor (opposite Delta) type_category :=
@functor.mk _ _ _ _ BD0_object (@BD0_morphism) BD0_respect_id
BD0_respect_comp

---

I could not replace "@functor.mk _ _ _ _" with "functor.mk", even though it
should mean the same thing. The four hidden arguments are

  nat Type (opposite Delta) type_category

which can be inferred from the asserted type of BD0.

I think what is happening is that because the last two arguments have type
"category nat" and "category Type" respectively, somehow the type class
inference is kicking in and failing, when the solution does not require
type classes at all. My current file is attached. (It compiles with the
version of category.lean in the main repository.)

I guess my question is: what happens if you replace "hom c d" with "@hom _
_ c d"?

By the way, Leo, I think it is really nice that the definition of BD0 type
checks. There is a lot of unwrapping going on to ensure that the arguments
really have the right type.
