### ISSUE TITLE
make process not working in user directories?

### ISSUE THREAD

**Issue by avigad** [leanprover/lean#232]
I am using fcdd527. I create a new directory "test" outside the lean directory. In emacs, I create a file "foo.lean", with

```
constant foo : Type
```

and save it.

Then I create a file "bar.lean" with

```
import .foo
```

I get:

```
invalid import, unknown module 'foo' (lean-checker)
```

The same happens if I write

```
import .foo
```

Running linja foo.lean does nothing in the test directory . I have to explicitly run

```
lean foo.lean -o foo.olean
```

before bar.lean can "see" foo.

If I return to emacs and change foo.lean (e.g. changing "foo : Type" to "foo2 : Type"), bar.lean doesn't "see" the change until I run lean explicitly.

**Comment by leodemoura** [comment]
When we have multiple files, we must use a "project" file.
The emacs lean menu has an option called "Create a new project".
A lean project is just a `.project` file. 
The menu option will create a default file. The default is good for almost everything.

**Comment by avigad** [comment]
I just tried it, and it works fine.

The file selection dialog box was confusing. I was given a list of files in the directory, and instructions that I could type "C-l" to get a "file name text entry box". Why not present the text field by default? Is this some emacs quirk?

Just hitting "open", however, did the right thing.

**Comment by soonhokong** [comment]
Unfortunately, it seems there are nothing much we can do with the file dialog. I can change the dialog title from "Project root: " to "Specify the project root directory: ". But that is almost all I can do.

Another solution is to disable dialog box:

``` elisp
(setq use-dialog-box nil)
```

With this setup, it will ask the location of project root at the mini-buffer just like find-file(<kbd>C-x C-f</kbd>). 

``` elisp
Project root: ~/project/lean/tmp/
```

Personally, I'm using this setup because you can still use `ido-mode` and other good packages.

**Comment by avigad** [comment]
No strong feelings here.

**Comment by soonhokong** [comment]
> I can change the dialog title from "Project root: " to "Specify the project root directory: ".

It's done by b6d475c3acf9e3608cfc58d7e4864d9cc3927550.

Let's close this issue.
