### ISSUE TITLE
linja: add '-k' option

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean#234]
```
       -k N   keep going until N jobs fail [default=1]
```

**Comment by soonhokong** [comment]
@avigad, I thought about whether we need to make `--keep-going` option a default one. I think it's best to keep `--keep-going` optional. I think it's important to make the default behavior of `linja` matched with the default behavior of GNU `make` and `ninja`.

I read [a chapter](https://www.gnu.org/software/make/manual/html_node/Testing.html#Testing) at GNU Make manual:

> The usual behavior of make assumes that your purpose is to get the goals up to date; once make learns that this is impossible, it might as well report the failure immediately. The ‘-k’ flag says that the real purpose is to test as much as possible of the changes made in the program, perhaps to find several independent problems so that you can correct them all before the next attempt to compile. **This is why Emacs’ M-x compile command passes the ‘-k’ flag by default**.

Following this convention, I can enable `--keep-going` option for `linja` on emacs. 

@avigad, if you use `linja` mostly via emacs, this can solve the problem. If you use `linja` on terminal frequently, then I can support a configuration file such as `.linja_option` where you can specify default options of `linja` for your project.

@leodemoura and @fpvandoorn, I'm happy to listen to your opinions as well.

**Comment by avigad** [comment]
I think the change to emacs is sufficient. That way if file a depends on b
and c, and b is broken but c works, then linja will try to keep c up to
date while the user works on a. If someone runs linja from the command
line, they will see explicitly what is broken.

The problem is that I compiled the library and didn't notice that something
was broken, and then I was surprised that when other imports did not work.
But it was easy to find the problem, and generally speaking the library
will be in good shape when we ship it.

**Comment by soonhokong** [comment]
I see. I'll make the change and close this issue.
