### ISSUE TITLE
deterministic class-instance resolution flag

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#265]
We should have a flag that signs an error whenever class-instance resolution generates more than one solution.

This issue came up in discussions with @nikswamy

**Comment by nikswamy** [comment]
Nice. If I understand correctly, this flag would cause Lean to signal an error at resolution time. That is, I may freely define any number of overlapping instances, but when I eventually try to use that class, I may get an error because there's more than one solution. That's very useful already. But, is it possible to produce a warning at definition time? i.e., as soon as I define an instance that overlaps with another.

**Comment by leodemoura** [comment]
@nikswamy I believe it is possible. We can add another flag that checks potential overlaping at definition time. When this flag is on, we would sign an error whenever the resulting type of two different instances can be unified. Example: instances for the `inhabited` class

```
inhabited_Prop : inhabited Prop
inhabited_nat   : inhabited nat
inhabited_prod {A B : Type} : inhabited A -> inhabited B -> inhabited (product A B)
inhabited_sum1 {A B : Type} : inhabited A -> inhabited (sum A B)
inhabited_sum2 {A B : Type} : inhabited B -> inhabited (sum A B)
...
```

In the example above, we would get an error when we define `inhabited_sum2` because the resultin type can be unified with `inhabited_sum1`. In this case, they are identical.
The test is not complete because the unification procedure is not complete.
