### ISSUE TITLE
computer freezes when unifier max steps is high

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#269]
In this file I did multiple stupid things, and the result is that my computer froze when I tried to compile it (not just Lean or emacs, but my complete OS didn't react to any input anymore):

https://github.com/fpvandoorn/lean/blob/fully_bundled/library/algebra/category/constructions.lean#L233

The stupid things are a combination of setting the unifier to a high max steps (`set_option unifier.max_steps 1000000`) and having a faulty + complicated definition below it.

**Comment by leodemoura** [comment]
It is sad, but modern OSes still freeze when there is a process consuming a lot of memory.
I also experience this behavior from time to time. Sometimes, it is even hard to kill the process that is consuming all the memory.
I can bet your computer froze because lean was consuming all the memory.
One possible workaround is to add a flag `--max-memory <size>`. It will kill lean whenever the limit is reached.

**Comment by leodemoura** [comment]
BTW, on Linux, you can use

```
ulimit -v KBYTES
```

to limit the amount of memory a process can use.
If you use it before invoking Emacs, then emacs and all its sub-processes (including lean) will have to respect the given limit.

**Comment by fpvandoorn** [comment]
Yes, it is likely that my computer froze since Lean used all memory. I'll try using either of these workarounds when I try to increase the unifier max steps next time.
