### ISSUE TITLE
Wrong error message when I have non-variable universe?

### ISSUE THREAD

**Issue by javra** [leanprover/lean#304]
I get the message

```
/home/javra/Programme/lean/lean/library/hott/axioms/ua.lean:39:49: error: type mismatch at definition 'foo', has type
  Π (A B : Type),
    A ≃ B → A ≈ B
but is expected to have type
  Π {A B : Type},
    A ≃ B → A ≈ B
```

when I make the universe index in ua.lean non-variable and add a theorem

```
theorem foo {A B : Type} (H : A ≃ B) : A ≈ B := @ua A B H
```

Instead I think it should tell my that A and B are in the wrong universe.

**Comment by leodemoura** [comment]
Lean automatically reveals hidden information when the "given" and "expected" types may seen identical in the error message. This trick fails in this case because of the "binder annotations" are different.
I will improve the trick and make it ignore binder annotations. It will fix this instance.
However, it is not a perfect solution.
