### ISSUE TITLE
cannot import nat...

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#321]
I have no idea what's happening here. 
When I try to compile `hott.trunc` in Emacs (using `C-c C-x`), I get the error `unknown declaration 'prod'`, at the moment that `data.nat.basic` is imported. However, `lean-mode` can still compile the whole file and doesn't give an error on the `import` line. Also, using `ninja`, the library compiles fine.

When I create a new document in `hott` with just the content `import standard` I get a similar error. If I create such a document in any other folder, I don't get the error.

I already recompiled everything using `ninja clean && ninja clean-olean && ninja`. Any ideas what's causing this? (I'm using the `release` version)

**Comment by leodemoura** [comment]
I recently had to break `prod.lean` into smaller files. Some automatically generated constructions need `prod` to be declared in the environment, and I need it available before types such as `decidable` are defined.
Could you check if you have `prod.lean` or `prod.olean` at `library\data`?

Could you also try to execute `make clean-olean` to delete all library files, and recompile them again?

Thanks,
Leo

**Comment by soonhokong** [comment]
It is possible that you have some residual files under /lean/library directory. If you still have a problem after following Leo's advice, please try:

``` bash
cd /PATH/TO/lean/library
git clean -fxd
```

**Comment by fpvandoorn** [comment]
I already deleted all library files with `ninja clean-olean`, but I got the same error after recompiling.
I didn't have any files matching `prod.*` in `library/data`.
I tried `git clean -fxd`, but (after recompiling) the problem persists.

**Comment by leodemoura** [comment]
I managed to reproduce the problem on my machine.
I'm currently investigating it.
It is really weird.

**Comment by fpvandoorn** [comment]
> I managed to reproduce the problem on my machine.

Okay, "good" (or maybe it's bad, but I'm sort-of glad it's not just me).

> It is really weird.

Yes, I agree. Especially that it matters in which folder your file is.

**Comment by leodemoura** [comment]
Found the problem.
When the `LEAN_PATH` environment variable is not set we use the following default value:

```
.:[path-to-lean-exe]/../library:[path-to-lean-exe]/../lib/lean
```

We can get the actual path by executing

```
lean --path
```

On my machine, I get

```
.:/home/leo/projects/lean/bin/../library:/home/leo/projects/lean/bin/../lib/lean
```

Note that, the first directory to be checked is the current directory `.`. This is the source of the problem.
Now, suppose we try to compile `truc.lean` at `library/hott`. It imports the file `data.nat.basic` which imports `logic`. When we search `logic` in the path we find one in the current directory `library/hott/logic`. This is the wrong one, `data.nat.basic` really wants `logic/default`.

The problem is to search the current directory _before_ we search the library directory. The correct default path should be

```
/home/leo/projects/lean/bin/../library:/home/leo/projects/lean/bin/../lib/lean:.
```

So a file in the current directory cannot "shadow" a library file.
I will submit the fix.

**Comment by leodemoura** [comment]
BTW, it works when we use `linja` because `linja` does "compile" the files in the "current" directory.

**Comment by fpvandoorn** [comment]
Good!
However, does this solve every case? 
If `c.lean` imports `b.lean` which imports `a.lean`, will `c` always import the same file `a` as `b` did? If `b` and `c` are in different folders, say `path_to_b/b` and `path_to_c/c` and there's a file named `a` in both folders, will `c` import `path_to_b/a`? 
I might be misunderstanding, but it sounds like it will import `path_to_c/a`. (if `a` was imported in `b` using `import a`, not `import .a`) (I'm on Windows right now, so I cannot easily try it).

**Comment by leodemoura** [comment]
> However, does this solve every case? 

The `.olean` files do not store absolute paths to imported files, but relative paths with respect to `LEAN_PATH`. To completely avoid the problem we would have to store absolute paths, but this has other problems. For example, an .olean generated on my machine would not work on yours.

In the example in your previous message, `b.olean` will store that it imported the file `path_to_b/a`. When we import `b.olean`, we search for `path_to_b/a` in the directories in `LEAN_PATH`. So, the problem you experienced will only happen if

1-  `LEAN_PATH` contains relative directories. (this was your case)
2-  the user compiles several files, then modifies `LEAN_PATH`, and then tries to load the compiled files.

If the `LEAN_PATH` contains only absolute paths, and we didn't change it since we generated `b.olean`, we will get the same `path_to_b/a`. 

In `truc.lean`,  `data/nat/basic.olean` stored that it imported `logic`, it means it imported `logic` from a root directory in the `LEAN_PATH`. The first directory in the `LEAN_PATH` was `.`. The meaning of `.` changes as we change directories. Then, we got a problem because the `truc.lean` contains a file called `logic.lean`.
