### ISSUE TITLE
intro tactic + variables [continued]

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean#332]
I found another bug with the `intro` tactic and variables in the context. If you use `intro a`, and `a` is a variable in the context, this will add the variable `a` as argument to the theorem:

```
import tools.tactic
variable {a : Type}
theorem foo {A : Type} : A → A :=
begin
intro a, exact a
end
check @foo
```

**Comment by leodemoura** [comment]
The tactics don't have a clear context. We only know the real context when we execute them.

The only fix I see is the following:
- When computing the set of used variables, we ignore variables occurring in tactics.
  The motivation is that we don't really know what is the context, and whether the variable is bound or not by the context.

I'm not sure if this is a good fix since it will probably generate other problems.
For example, should the following example be accepted?

```
import tools.tactic
variables {A : Type} {a : A}
theorem foo : A → A :=
begin
intros,
exact a
end
```

Right now, it is, but if I implement the modification it will not.
One workaround would be to use `include a` in this kind of situation.
What do you think?

**Comment by fpvandoorn** [comment]
This is indeed harder than I thought. 
I think the fix is reasonable. Most of the time, variables which should be included in a theorem will be mentioned in the type of the theorem (perhaps implicitly). 
In my work with Lean the only times where this was not the case is when the variable is a class instance, but then you'll have to write `include` anyway.

**Comment by avigad** [comment]
I don't fully understand the problem. Is it that in Floris' example, Lean
doesn't know that "exact a" refers to the locally introduced a, not the
context?

The fix sounds reasonable -- if the error messages are reasonable, the user
can explicitly include the variable. (Remind me: can the user still
"include a" when stating the theorem?)

**Comment by fpvandoorn** [comment]
No, the proof does what you want it to do.
What happens is that before elaborating the proof, Lean checks which variables are used in the theorem. It sees an `exact a` in the proof, so it inserts the variable `a` to the type of the theorem.
In general it's hard to figure out whether an `a` in a tactic refers to an `a` previously introduces with `intro a` or whether it refers to the variable in the context (because the goal where you applied `intro a` could already be solved).
