### ISSUE TITLE
namespace management

### ISSUE THREAD

**Issue by avigad** [leanprover/lean#36]
Implement the following behavior for namespaces:

``` lean
  namespace foo
    theorem bar : ...
  end foo
```

creates identifier foo.bar.

"import" and "namespace" are kept orthogonal (file structure has nothing to do with namespace structure).

The command

```
  open foo [as bar] [using / hiding / renaming]
```

does the following (conceptually):

(1) gathers all the theorems in foo, removing "foo"
(2) picks out the ones indicated by using / hiding
(3) renames according to renaming
(4) creates aliases, prepending "bar" if present

The command

```
  export foo [as bar] [using / hiding / renaming]
```

does the same thing but creates permanent abbreviations rather than transient aliases.

Question: should we have special syntax for opening / exporting a single theorem? E.g.

```
  open foo bar
```

or

```
  open foo (bar)
```

for 

```
  open foo (using bar)
```

Inside a module, a theorem or definition can be marked as "private", which means that it is never opened or exported. It can also be marked as "protected", which means that it is never opened or exported unless the user explicitly asks for it.

Question: what should the syntax for that be? We can require that it is on an explicit "using" list. In that case, the user would have to say

```
  open nat
  open nat (using induction_on)
```

possibly with the shorthand above. Another option is to add another modifier, "including", which can be used in the absence of using. So

```
  open nat (including induction_on)
```

would have the same meaning as the two lines above.

Add options to flag an error or warning if identifies become overloaded, and also if notation conflicts.

A command

```
  theorem foo [in bar] ...
```

puts the theorem in bar (i.e. calls it bar.foo) but also uses it, i.e. creates an alias.

The command

```
  inductive foo : Type :=
  | bar : ...
  | baz : ...
```

creates constants foo, foo.mk, foo.rec, foo.bar, foo.baz, and similarly for "structure".

The construct 

```
  section

  end
```

should be used to set parameters common to all theorems. Notations, rewrites, and so on are persistent.

The construct

```
  context

  end
```

should be used to set up a local context. Notations, rewrites, and so on are transient.

**Comment by leodemoura** [comment]
@soonhokong and I discussed the new `inductive` command.
The new approach seems to have some problems. 
Users would have to declare inductive datatypes such as `nat` outside of the namespace `nat`. Otherwise, they would get `nat.nat.succ` and `nat.nat.zero`. When we discussed this approach, I suggested the "hack" that would merge `N.N` into `N` to avoid this kind of problem. @soonhokong thinks this is too hackish. I agree with him. The rules for namespace management should be uniform and clean.
It seems we would have to keep using the following idiom (that may look quite weird to newcomers). 

```
       inductive nat :=
       zero : nat,
       succ : nat -> nat

       namespace nat
           -- theorems and definitions
           ...
       end nat
```

BTW, we didn't find a good/better solution. We discussed many alternatives and all of them have "little" problems.

**Comment by leodemoura** [comment]
Here is a update for the other items in this issue.

The `using` command has been renamed to `open`.
The `as` directive has been added.
The `[protected]` modifier has be added. We can declare theorems/definitions as "protected".
The `export` command has been added.
The `context` command has been added.

```
       open foo (def1 def2)
```

is the notation for using only `foo.def1` and `foo.def2`.

Remarks:
1) Notations cannot really be persistent. They have a different meaning inside/outside of the section.
In the following section

```
       section foo
              parameter A : Type
              variable f : A -> A -> A
              infixl `++` := f
              ...
       end foo
```

The notation `a ++ b` means `f A a b`. It doesn't make sense outside of the section because `A` is not in the scope anymore.

2) The notation `[in bar]` seems too hackish. It seems there is only one place on the standard library where it would be useful is

```
     namespace path
         abbreviation induction_on [protected] {A : Type} {a b : A} (p : a ≈ b)
             {C : Π (b : A) (p : a ≈ b), Type} (H : C a (idpath a)) : C b p :=
         path_rec H p
     end path
     open path
```

Even this instance is not really clear. It also contains the comment

```
               -- TODO: should all this be in namespace path?
```

**Comment by avigad** [comment]
I agree that the nat.nat collapse trick is a hack, and we should avoid it. 

The idiom of defining the type outside the namespace and then starting the namespace right after is what I had in mind. It is what we are currently doing in lots of the modules in data/, like data/sigma.lean. It seems to me to be the natural way of dealing with the fact that we often want the namespace to have the same name as the type.

It seems to provide all the necessary flexibility. If the user instead wants the datatype to be nat.type, she can define inductive "type" in the nat namespace. Or the user could define type in the namespace nat, and then define 

  abbreviation nat := nat.type

outside the namespace, etc.

I agree with all the comments and the changes sound good.

**Comment by leodemoura** [comment]
I still have to cleanup the library, but all the new approach for naming intro and rec has been implemented.
