### ISSUE TITLE
multi-line comments in emacs mode

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean#63]
Lean supports multi-line comments of the form
     (--  
        this is a comment
     --)

The emacs mode does not highlight them correctly.

**Comment by soonhokong** [comment]
Partially implemented by 51b86b219b7ebc813fd10d63e2e83d0c683b6ae9:

Two known issues:
- Emacs behaves as if the multi-line comment start/end symols are "**(-**" and "**-)**" instead of "**(--**" and "**--)**". As a result, it shows all the correct lean comments as it is. However, it will show some examples such as "(-5)" as a part of comment even if Lean doesn't interpret it as it is. Technically, it's because we are using a syntax-table based method to define comments. For more information read a documentation of '[modify-syntax-entry](http://www.emacswiki.org/emacs/EmacsSyntaxTable)' function.
- Somehow, the matching parens are broken. When we type "--)" to close a multi-line comment. Emacs warns "Mismatched Parentheses".

**Comment by shlevy** [comment]
This seems to be broken still.

**Comment by fpvandoorn** [comment]
multi-line comments are now written

```
/-
this is a comment
-/
```
