### ISSUE TITLE
make sections persistent, contexts transient

### ISSUE THREAD

**Issue by avigad** [leanprover/lean#88]
use "section ... end" for declarations that persist, "context ... end" for ones that are temporary.

**Comment by leodemoura** [comment]
Summary: I implemented the `contexts`. However, the not everything is persistent in a section. 
The notation defined inside of a section may only make sense inside of the section.

```
     section tst
         parameter A : Type
         definition f (a b : A) := a
         infixl `#`:65 := f   -- f here means (f A)
     end tst

     variables a b : nat
     check a # b   ---- <<< Error: `A` is not defined
```

A notation declaration in a section only makes sense if all parameters are implicit.
Even this case is fishy, since it would confuse users. Suppose `A` in the example above is implicit. Then `0 # 1` would work inside the section (it shouldn't).
